import type { Conversation } from "@/types/conversation";
import type { Message } from "@/types/message";
import type { Contact } from "@/types/contact";
import type { KpiCardData, VendedorData, ChartDataPoint } from "@/types/report";
import type { InternalNote } from "@/types/note";

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "c1",
    workspaceId: "w1",
    name: "Ana Silva",
    phone: "+55 34 9 9999-1234",
    email: "ana.silva@email.com",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u1",
    createdAt: "2026-04-10T14:30:00Z",
    updatedAt: "2026-04-14T10:45:00Z",
    tags: [
      { id: "t1", workspaceId: "w1", name: "Lead Quente", color: "#D94F3A" },
      { id: "t2", workspaceId: "w1", name: "Retorno", color: "#128C7E" },
    ],
  },
  {
    id: "c2",
    workspaceId: "w1",
    name: "Carlos Mendes",
    phone: "+55 11 9 8765-4321",
    email: null,
    avatarUrl: null,
    notes: null,
    assignedUserId: "u2",
    createdAt: "2026-04-12T09:00:00Z",
    updatedAt: "2026-04-14T10:32:00Z",
  },
  {
    id: "c3",
    workspaceId: "w1",
    name: "Beatriz Costa",
    phone: "+55 21 9 7654-3210",
    email: null,
    avatarUrl: null,
    notes: null,
    assignedUserId: null,
    createdAt: "2026-04-13T08:00:00Z",
    updatedAt: "2026-04-14T10:18:00Z",
  },
  {
    id: "c4",
    workspaceId: "w1",
    name: "Pedro Santos",
    phone: "+55 31 9 6543-2100",
    email: null,
    avatarUrl: null,
    notes: null,
    assignedUserId: "u1",
    createdAt: "2026-04-09T10:00:00Z",
    updatedAt: "2026-04-14T09:54:00Z",
  },
  {
    id: "c5",
    workspaceId: "w1",
    name: "Mariana Lima",
    phone: "+55 41 9 5432-1098",
    email: null,
    avatarUrl: null,
    notes: null,
    assignedUserId: "u2",
    createdAt: "2026-04-11T15:00:00Z",
    updatedAt: "2026-04-14T09:41:00Z",
  },
  {
    id: "c6",
    workspaceId: "w1",
    name: "Roberto Alves",
    phone: "+55 51 9 4321-0987",
    email: null,
    avatarUrl: null,
    notes: null,
    assignedUserId: "u1",
    createdAt: "2026-04-08T12:00:00Z",
    updatedAt: "2026-04-13T18:00:00Z",
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv1",
    workspaceId: "w1",
    contactId: "c1",
    instanceId: "inst1",
    assignedUserId: "u1",
    status: "OPEN",
    unreadCount: 2,
    lastMessageAt: "2026-04-14T10:45:00Z",
    lastMessagePreview: "Olá! Gostaria de saber mais sobre os pla...",
    createdAt: "2026-04-14T10:30:00Z",
    resolvedAt: null,
    contact: MOCK_CONTACTS[0],
  },
  {
    id: "conv2",
    workspaceId: "w1",
    contactId: "c2",
    instanceId: "inst1",
    assignedUserId: "u2",
    status: "RESOLVED",
    unreadCount: 0,
    lastMessageAt: "2026-04-14T10:32:00Z",
    lastMessagePreview: "Perfeito, muito obrigado pela ajuda!",
    createdAt: "2026-04-14T09:00:00Z",
    resolvedAt: "2026-04-14T10:32:00Z",
    contact: MOCK_CONTACTS[1],
  },
  {
    id: "conv3",
    workspaceId: "w1",
    contactId: "c3",
    instanceId: "inst1",
    assignedUserId: null,
    status: "UNASSIGNED",
    unreadCount: 1,
    lastMessageAt: "2026-04-14T10:18:00Z",
    lastMessagePreview: "Quando podemos agendar uma demons...",
    createdAt: "2026-04-14T10:18:00Z",
    resolvedAt: null,
    contact: MOCK_CONTACTS[2],
  },
  {
    id: "conv4",
    workspaceId: "w1",
    contactId: "c4",
    instanceId: "inst1",
    assignedUserId: "u1",
    status: "WAITING_CUSTOMER",
    unreadCount: 0,
    lastMessageAt: "2026-04-14T09:54:00Z",
    lastMessagePreview: "Recebi o orçamento, vou analisar",
    createdAt: "2026-04-13T14:00:00Z",
    resolvedAt: null,
    contact: MOCK_CONTACTS[3],
  },
  {
    id: "conv5",
    workspaceId: "w1",
    contactId: "c5",
    instanceId: "inst1",
    assignedUserId: "u2",
    status: "OPEN",
    unreadCount: 3,
    lastMessageAt: "2026-04-14T09:41:00Z",
    lastMessagePreview: "Qual é o prazo de entrega?",
    createdAt: "2026-04-13T16:00:00Z",
    resolvedAt: null,
    contact: MOCK_CONTACTS[4],
  },
  {
    id: "conv6",
    workspaceId: "w1",
    contactId: "c6",
    instanceId: "inst1",
    assignedUserId: "u1",
    status: "RESOLVED",
    unreadCount: 0,
    lastMessageAt: "2026-04-13T18:00:00Z",
    lastMessagePreview: "Obrigado! Problema resolvido",
    createdAt: "2026-04-10T10:00:00Z",
    resolvedAt: "2026-04-13T18:00:00Z",
    contact: MOCK_CONTACTS[5],
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "m1",
    conversationId: "conv1",
    contactId: "c1",
    direction: "INBOUND",
    type: "TEXT",
    content: "Olá! Bom dia",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam1",
    sentByUserId: null,
    createdAt: "2026-04-14T10:30:00Z",
  },
  {
    id: "m2",
    conversationId: "conv1",
    contactId: "c1",
    direction: "INBOUND",
    type: "TEXT",
    content: "Gostaria de saber mais sobre os planos disponíveis",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam2",
    sentByUserId: null,
    createdAt: "2026-04-14T10:30:30Z",
  },
  {
    id: "m3",
    conversationId: "conv1",
    contactId: "c1",
    direction: "OUTBOUND",
    type: "TEXT",
    content: "Bom dia! Claro, ficarei feliz em ajudar. Temos três planos principais: Básico, Profissional e Empresarial.",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam3",
    sentByUserId: "u1",
    createdAt: "2026-04-14T10:32:00Z",
  },
  {
    id: "m4",
    conversationId: "conv1",
    contactId: "c1",
    direction: "OUTBOUND",
    type: "TEXT",
    content: "Cada um oferece diferentes recursos e capacidades. Qual seria o tamanho da sua operação?",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam4",
    sentByUserId: "u1",
    createdAt: "2026-04-14T10:32:30Z",
  },
  {
    id: "m5",
    conversationId: "conv1",
    contactId: "c1",
    direction: "INBOUND",
    type: "TEXT",
    content: "Temos uma equipe de cerca de 15 pessoas",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam5",
    sentByUserId: null,
    createdAt: "2026-04-14T10:35:00Z",
  },
  {
    id: "m6",
    conversationId: "conv1",
    contactId: "c1",
    direction: "OUTBOUND",
    type: "TEXT",
    content: "Perfeito! Para 15 pessoas, recomendo o plano Profissional. Vou enviar os detalhes:",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam6",
    sentByUserId: "u1",
    createdAt: "2026-04-14T10:36:00Z",
  },
  {
    id: "m7",
    conversationId: "conv1",
    contactId: "c1",
    direction: "OUTBOUND",
    type: "IMAGE",
    content: null,
    mediaUrl: "/placeholder-plan.png",
    mediaType: "image/png",
    status: "DELIVERED",
    whatsappMessageId: "wam7",
    sentByUserId: "u1",
    createdAt: "2026-04-14T10:36:30Z",
  },
];

export const MOCK_NOTES: InternalNote[] = [
  {
    id: "n1",
    conversationId: "conv1",
    userId: "u2",
    userName: "João Silva",
    content: "Cliente demonstrou interesse em plano empresarial. Agendar follow-up.",
    createdAt: "2026-04-14T09:30:00Z",
  },
  {
    id: "n2",
    conversationId: "conv1",
    userId: "u1",
    userName: "Maria Santos",
    content: "Já realizou compra anterior. Cliente fidelizado.",
    createdAt: "2026-04-12T15:20:00Z",
  },
];

// ── Dashboard ──

export const MOCK_KPI_CARDS: KpiCardData[] = [
  {
    label: "Conversas Abertas",
    value: "142",
    change: "+12%",
    trend: "up",
    trendIsPositive: true,
    icon: "conversations",
  },
  {
    label: "Tempo Médio de Resposta",
    value: "2m 45s",
    change: "-8%",
    trend: "down",
    trendIsPositive: true,
    icon: "clock",
  },
  {
    label: "Atendimentos Hoje",
    value: "87",
    change: "+24%",
    trend: "up",
    trendIsPositive: true,
    icon: "check",
  },
  {
    label: "Leads Novos",
    value: "34",
    change: "+18%",
    trend: "up",
    trendIsPositive: true,
    icon: "user-plus",
  },
];

export const MOCK_CHART_DATA: ChartDataPoint[] = [
  { date: "15 Mar", conversas: 35 },
  { date: "16 Mar", conversas: 42 },
  { date: "17 Mar", conversas: 50 },
  { date: "18 Mar", conversas: 48 },
  { date: "19 Mar", conversas: 55 },
  { date: "20 Mar", conversas: 52 },
  { date: "21 Mar", conversas: 60 },
  { date: "22 Mar", conversas: 58 },
  { date: "23 Mar", conversas: 65 },
  { date: "24 Mar", conversas: 70 },
  { date: "25 Mar", conversas: 68 },
  { date: "26 Mar", conversas: 75 },
  { date: "27 Mar", conversas: 80 },
  { date: "28 Mar", conversas: 78 },
  { date: "29 Mar", conversas: 85 },
  { date: "30 Mar", conversas: 82 },
  { date: "31 Mar", conversas: 90 },
  { date: "2 Abr", conversas: 88 },
  { date: "4 Abr", conversas: 95 },
  { date: "6 Abr", conversas: 100 },
  { date: "8 Abr", conversas: 105 },
  { date: "10 Abr", conversas: 110 },
  { date: "12 Abr", conversas: 120 },
  { date: "13 Abr", conversas: 130 },
];

export const MOCK_VENDEDORES: VendedorData[] = [
  { nome: "Maria Silva", atendimentos: 142, tempoMedio: "2m 30s", conversoes: 89, taxa: 62.7 },
  { nome: "João Santos", atendimentos: 128, tempoMedio: "3m 15s", conversoes: 76, taxa: 59.4 },
  { nome: "Ana Costa", atendimentos: 115, tempoMedio: "2m 45s", conversoes: 68, taxa: 59.1 },
  { nome: "Pedro Lima", atendimentos: 98, tempoMedio: "4m 10s", conversoes: 52, taxa: 53.1 },
  { nome: "Carla Souza", atendimentos: 87, tempoMedio: "3m 30s", conversoes: 45, taxa: 51.7 },
];
