import type { Conversation } from "@/types/conversation";
import type { Message } from "@/types/message";
import type { Contact, ContactTableRow, ConversaHistorico, NotaInterna } from "@/types/contact";
import type { Tag } from "@/types/tag";
import type { KpiCardData, VendedorData, ChartDataPoint } from "@/types/report";
import type { InternalNote } from "@/types/note";
import type { NumberCardData } from "@/types/instance";
import { INSTANCE_COLORS } from "@/lib/constants";

export const MOCK_TAGS: Tag[] = [
  { id: "t1", workspaceId: "w1", name: "Lead Quente", color: "#D94F3A" },
  { id: "t2", workspaceId: "w1", name: "Vendas", color: "#4f5a63" },
  { id: "t3", workspaceId: "w1", name: "Cliente", color: "#4CAF50" },
  { id: "t4", workspaceId: "w1", name: "Demonstração", color: "#F59E0B" },
  { id: "t5", workspaceId: "w1", name: "VIP", color: "#7C3AED" },
  { id: "t6", workspaceId: "w1", name: "Suporte", color: "#4CAF50" },
  { id: "t7", workspaceId: "w1", name: "Lead Frio", color: "#8a96a3" },
  { id: "t8", workspaceId: "w1", name: "Retorno", color: "#128C7E" },
  { id: "t9", workspaceId: "w1", name: "Orçamento", color: "#F59E0B" },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "c1",
    workspaceId: "w1",
    name: "Ana Silva",
    phone: "+55 34 9 9999-1234",
    email: "ana.silva@empresa.com",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u1",
    createdAt: "2026-04-10T14:30:00Z",
    updatedAt: "2026-04-15T08:00:00Z",
    tags: [MOCK_TAGS[0], MOCK_TAGS[1]],
  },
  {
    id: "c2",
    workspaceId: "w1",
    name: "Carlos Mendes",
    phone: "+55 21 9 8888-2345",
    email: "carlos.mendes@tech.com",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u2",
    createdAt: "2026-04-12T09:00:00Z",
    updatedAt: "2026-04-14T10:00:00Z",
    tags: [MOCK_TAGS[2]],
  },
  {
    id: "c3",
    workspaceId: "w1",
    name: "Beatriz Costa",
    phone: "+55 11 9 7777-3456",
    email: "beatriz@startup.io",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u3",
    createdAt: "2026-04-13T08:00:00Z",
    updatedAt: "2026-04-15T07:00:00Z",
    tags: [MOCK_TAGS[0], MOCK_TAGS[3]],
  },
  {
    id: "c4",
    workspaceId: "w1",
    name: "Pedro Santos",
    phone: "+55 47 9 6666-4567",
    email: "pedro.santos@corp.com.br",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u4",
    createdAt: "2026-04-09T10:00:00Z",
    updatedAt: "2026-04-10T10:00:00Z",
    tags: [MOCK_TAGS[2], MOCK_TAGS[4]],
  },
  {
    id: "c5",
    workspaceId: "w1",
    name: "Mariana Lima",
    phone: "+55 85 9 5555-5678",
    email: "mariana.lima@gmail.com",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u5",
    createdAt: "2026-04-11T15:00:00Z",
    updatedAt: "2026-04-15T09:30:00Z",
    tags: [MOCK_TAGS[5]],
  },
  {
    id: "c6",
    workspaceId: "w1",
    name: "Roberto Alves",
    phone: "+55 61 9 4444-6789",
    email: "roberto@consultoria.com",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u6",
    createdAt: "2026-04-08T12:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
    tags: [MOCK_TAGS[6]],
  },
  {
    id: "c7",
    workspaceId: "w1",
    name: "Julia Mendes",
    phone: "+55 19 9 3333-7890",
    email: "julia.mendes@design.studio",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u3",
    createdAt: "2026-04-07T11:00:00Z",
    updatedAt: "2026-04-15T09:00:00Z",
    tags: [MOCK_TAGS[2], MOCK_TAGS[7]],
  },
  {
    id: "c8",
    workspaceId: "w1",
    name: "Fernando Dias",
    phone: "+55 27 9 2222-8901",
    email: "fernando.dias@industria.com.br",
    avatarUrl: null,
    notes: null,
    assignedUserId: "u7",
    createdAt: "2026-04-06T09:00:00Z",
    updatedAt: "2026-04-15T06:00:00Z",
    tags: [MOCK_TAGS[0], MOCK_TAGS[8]],
  },
];

// Dados enriquecidos para a tabela de contatos (simula JOIN com conversas e usuários)
export const MOCK_CONTACTS_TABLE: ContactTableRow[] = [
  { contact: MOCK_CONTACTS[0], responsavel: "Maria Silva", conversasCount: 8, ultimoContato: "2026-04-15T08:00:00Z" },
  { contact: MOCK_CONTACTS[1], responsavel: "João Santos", conversasCount: 24, ultimoContato: "2026-04-14T10:00:00Z" },
  { contact: MOCK_CONTACTS[2], responsavel: "Ana Costa", conversasCount: 5, ultimoContato: "2026-04-15T07:00:00Z" },
  { contact: MOCK_CONTACTS[3], responsavel: "Pedro Lima", conversasCount: 42, ultimoContato: "2026-04-10T10:00:00Z" },
  { contact: MOCK_CONTACTS[4], responsavel: "Carla Souza", conversasCount: 12, ultimoContato: "2026-04-15T09:30:00Z" },
  { contact: MOCK_CONTACTS[5], responsavel: "Roberto Alves", conversasCount: 2, ultimoContato: "2026-04-01T10:00:00Z" },
  { contact: MOCK_CONTACTS[6], responsavel: "Beatriz Costa", conversasCount: 18, ultimoContato: "2026-04-15T09:00:00Z" },
  { contact: MOCK_CONTACTS[7], responsavel: "Lucas Ferreira", conversasCount: 6, ultimoContato: "2026-04-15T06:00:00Z" },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv1",
    workspaceId: "w1",
    contactId: "c1",
    instanceId: "inst1",
    assignedUserId: "u1",
    status: "OPEN",
    unreadCount: 2,
    lastMessageAt: "2026-04-14T10:45:00Z",
    lastMessagePreview: "Olá! Gostaria de saber mais sobre os pla...",
    createdAt: "2026-04-14T10:30:00Z",
    resolvedAt: null,
    contact: MOCK_CONTACTS[0],
  },
  {
    id: "conv2",
    workspaceId: "w1",
    contactId: "c2",
    instanceId: "inst1",
    assignedUserId: "u2",
    status: "RESOLVED",
    unreadCount: 0,
    lastMessageAt: "2026-04-14T10:32:00Z",
    lastMessagePreview: "Perfeito, muito obrigado pela ajuda!",
    createdAt: "2026-04-14T09:00:00Z",
    resolvedAt: "2026-04-14T10:32:00Z",
    contact: MOCK_CONTACTS[1],
  },
  {
    id: "conv3",
    workspaceId: "w1",
    contactId: "c3",
    instanceId: "inst1",
    assignedUserId: null,
    status: "UNASSIGNED",
    unreadCount: 1,
    lastMessageAt: "2026-04-14T10:18:00Z",
    lastMessagePreview: "Quando podemos agendar uma demons...",
    createdAt: "2026-04-14T10:18:00Z",
    resolvedAt: null,
    contact: MOCK_CONTACTS[2],
  },
  {
    id: "conv4",
    workspaceId: "w1",
    contactId: "c4",
    instanceId: "inst1",
    assignedUserId: "u1",
    status: "WAITING_CUSTOMER",
    unreadCount: 0,
    lastMessageAt: "2026-04-14T09:54:00Z",
    lastMessagePreview: "Recebi o orçamento, vou analisar",
    createdAt: "2026-04-13T14:00:00Z",
    resolvedAt: null,
    contact: MOCK_CONTACTS[3],
  },
  {
    id: "conv5",
    workspaceId: "w1",
    contactId: "c5",
    instanceId: "inst1",
    assignedUserId: "u2",
    status: "OPEN",
    unreadCount: 3,
    lastMessageAt: "2026-04-14T09:41:00Z",
    lastMessagePreview: "Qual é o prazo de entrega?",
    createdAt: "2026-04-13T16:00:00Z",
    resolvedAt: null,
    contact: MOCK_CONTACTS[4],
  },
  {
    id: "conv6",
    workspaceId: "w1",
    contactId: "c6",
    instanceId: "inst1",
    assignedUserId: "u1",
    status: "RESOLVED",
    unreadCount: 0,
    lastMessageAt: "2026-04-13T18:00:00Z",
    lastMessagePreview: "Obrigado! Problema resolvido",
    createdAt: "2026-04-10T10:00:00Z",
    resolvedAt: "2026-04-13T18:00:00Z",
    contact: MOCK_CONTACTS[5],
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "m1",
    conversationId: "conv1",
    contactId: "c1",
    direction: "INBOUND",
    type: "TEXT",
    content: "Olá! Bom dia",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam1",
    sentByUserId: null,
    createdAt: "2026-04-14T10:30:00Z",
  },
  {
    id: "m2",
    conversationId: "conv1",
    contactId: "c1",
    direction: "INBOUND",
    type: "TEXT",
    content: "Gostaria de saber mais sobre os planos disponíveis",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam2",
    sentByUserId: null,
    createdAt: "2026-04-14T10:30:30Z",
  },
  {
    id: "m3",
    conversationId: "conv1",
    contactId: "c1",
    direction: "OUTBOUND",
    type: "TEXT",
    content: "Bom dia! Claro, ficarei feliz em ajudar. Temos três planos principais: Básico, Profissional e Empresarial.",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam3",
    sentByUserId: "u1",
    createdAt: "2026-04-14T10:32:00Z",
  },
  {
    id: "m4",
    conversationId: "conv1",
    contactId: "c1",
    direction: "OUTBOUND",
    type: "TEXT",
    content: "Cada um oferece diferentes recursos e capacidades. Qual seria o tamanho da sua operação?",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam4",
    sentByUserId: "u1",
    createdAt: "2026-04-14T10:32:30Z",
  },
  {
    id: "m5",
    conversationId: "conv1",
    contactId: "c1",
    direction: "INBOUND",
    type: "TEXT",
    content: "Temos uma equipe de cerca de 15 pessoas",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam5",
    sentByUserId: null,
    createdAt: "2026-04-14T10:35:00Z",
  },
  {
    id: "m6",
    conversationId: "conv1",
    contactId: "c1",
    direction: "OUTBOUND",
    type: "TEXT",
    content: "Perfeito! Para 15 pessoas, recomendo o plano Profissional. Vou enviar os detalhes:",
    mediaUrl: null,
    mediaType: null,
    status: "READ",
    whatsappMessageId: "wam6",
    sentByUserId: "u1",
    createdAt: "2026-04-14T10:36:00Z",
  },
  {
    id: "m7",
    conversationId: "conv1",
    contactId: "c1",
    direction: "OUTBOUND",
    type: "IMAGE",
    content: null,
    mediaUrl: "/placeholder-plan.png",
    mediaType: "image/png",
    status: "DELIVERED",
    whatsappMessageId: "wam7",
    sentByUserId: "u1",
    createdAt: "2026-04-14T10:36:30Z",
  },
];

export const MOCK_NOTES: InternalNote[] = [
  {
    id: "n1",
    conversationId: "conv1",
    userId: "u2",
    userName: "João Silva",
    content: "Cliente demonstrou interesse em plano empresarial. Agendar follow-up.",
    createdAt: "2026-04-14T09:30:00Z",
  },
  {
    id: "n2",
    conversationId: "conv1",
    userId: "u1",
    userName: "Maria Santos",
    content: "Já realizou compra anterior. Cliente fidelizado.",
    createdAt: "2026-04-12T15:20:00Z",
  },
];

// ── Dashboard ──

export const MOCK_KPI_CARDS: KpiCardData[] = [
  {
    label: "Conversas Abertas",
    value: "142",
    change: "+12%",
    trend: "up",
    trendIsPositive: true,
    icon: "conversations",
  },
  {
    label: "Tempo Médio de Resposta",
    value: "2m 45s",
    change: "-8%",
    trend: "down",
    trendIsPositive: true,
    icon: "clock",
  },
  {
    label: "Atendimentos Hoje",
    value: "87",
    change: "+24%",
    trend: "up",
    trendIsPositive: true,
    icon: "check",
  },
  {
    label: "Leads Novos",
    value: "34",
    change: "+18%",
    trend: "up",
    trendIsPositive: true,
    icon: "user-plus",
  },
];

export const MOCK_CHART_DATA: ChartDataPoint[] = [
  { date: "15 Mar", conversas: 35 },
  { date: "16 Mar", conversas: 42 },
  { date: "17 Mar", conversas: 50 },
  { date: "18 Mar", conversas: 48 },
  { date: "19 Mar", conversas: 55 },
  { date: "20 Mar", conversas: 52 },
  { date: "21 Mar", conversas: 60 },
  { date: "22 Mar", conversas: 58 },
  { date: "23 Mar", conversas: 65 },
  { date: "24 Mar", conversas: 70 },
  { date: "25 Mar", conversas: 68 },
  { date: "26 Mar", conversas: 75 },
  { date: "27 Mar", conversas: 80 },
  { date: "28 Mar", conversas: 78 },
  { date: "29 Mar", conversas: 85 },
  { date: "30 Mar", conversas: 82 },
  { date: "31 Mar", conversas: 90 },
  { date: "2 Abr", conversas: 88 },
  { date: "4 Abr", conversas: 95 },
  { date: "6 Abr", conversas: 100 },
  { date: "8 Abr", conversas: 105 },
  { date: "10 Abr", conversas: 110 },
  { date: "12 Abr", conversas: 120 },
  { date: "13 Abr", conversas: 130 },
];

export const MOCK_VENDEDORES: VendedorData[] = [
  { nome: "Maria Silva", atendimentos: 142, tempoMedio: "2m 30s", conversoes: 89, taxa: 62.7 },
  { nome: "João Santos", atendimentos: 128, tempoMedio: "3m 15s", conversoes: 76, taxa: 59.4 },
  { nome: "Ana Costa", atendimentos: 115, tempoMedio: "2m 45s", conversoes: 68, taxa: 59.1 },
  { nome: "Pedro Lima", atendimentos: 98, tempoMedio: "4m 10s", conversoes: 52, taxa: 53.1 },
  { nome: "Carla Souza", atendimentos: 87, tempoMedio: "3m 30s", conversoes: 45, taxa: 51.7 },
];

// ── Contatos: Histórico de conversas ──

export const MOCK_HISTORICO: Record<string, ConversaHistorico[]> = {
  c1: [
    { id: "h1", data: "2026-04-15T08:00:00Z", descricao: "Solicitou informações sobre plano empresarial", atendidoPor: "Maria Silva", duracao: "15 min" },
    { id: "h2", data: "2026-04-12T14:20:00Z", descricao: "Follow-up sobre proposta comercial enviada", atendidoPor: "Maria Silva", duracao: "20 min" },
    { id: "h3", data: "2026-04-10T14:30:00Z", descricao: "Primeiro contato via indicação", atendidoPor: "Sistema", duracao: "" },
  ],
  c2: [
    { id: "h4", data: "2026-04-14T10:45:00Z", descricao: "Cliente solicitou informações sobre plano empresarial", atendidoPor: "Maria Silva", duracao: "15 min" },
    { id: "h5", data: "2026-04-12T14:20:00Z", descricao: "Demonstração do produto realizada com sucesso", atendidoPor: "Maria Silva", duracao: "45 min" },
    { id: "h6", data: "2026-04-10T14:30:00Z", descricao: "Primeiro contato via formulário do site", atendidoPor: "Sistema", duracao: "" },
  ],
  c3: [
    { id: "h7", data: "2026-04-15T07:00:00Z", descricao: "Agendamento de demonstração confirmado", atendidoPor: "Ana Costa", duracao: "10 min" },
    { id: "h8", data: "2026-04-13T09:00:00Z", descricao: "Lead qualificado via campanha de marketing", atendidoPor: "Sistema", duracao: "" },
  ],
  c4: [
    { id: "h9", data: "2026-04-10T10:00:00Z", descricao: "Renovação de contrato discutida", atendidoPor: "Pedro Lima", duracao: "30 min" },
    { id: "h10", data: "2026-04-05T16:00:00Z", descricao: "Suporte técnico para integração de API", atendidoPor: "Pedro Lima", duracao: "1h 20 min" },
    { id: "h11", data: "2026-03-20T11:00:00Z", descricao: "Onboarding do cliente VIP concluído", atendidoPor: "Maria Silva", duracao: "2h" },
  ],
  c5: [
    { id: "h12", data: "2026-04-15T09:30:00Z", descricao: "Ticket de suporte resolvido", atendidoPor: "Carla Souza", duracao: "25 min" },
    { id: "h13", data: "2026-04-14T08:00:00Z", descricao: "Reportou erro na plataforma", atendidoPor: "Carla Souza", duracao: "15 min" },
  ],
  c6: [
    { id: "h14", data: "2026-04-01T10:00:00Z", descricao: "Email de follow-up enviado sem resposta", atendidoPor: "Roberto Alves", duracao: "5 min" },
    { id: "h15", data: "2026-03-15T14:00:00Z", descricao: "Primeiro contato via LinkedIn", atendidoPor: "Sistema", duracao: "" },
  ],
  c7: [
    { id: "h16", data: "2026-04-15T09:00:00Z", descricao: "Retorno sobre proposta de design", atendidoPor: "Beatriz Costa", duracao: "35 min" },
    { id: "h17", data: "2026-04-13T11:00:00Z", descricao: "Apresentação de portfólio de serviços", atendidoPor: "Beatriz Costa", duracao: "50 min" },
    { id: "h18", data: "2026-04-07T11:00:00Z", descricao: "Cliente indicada por parceiro", atendidoPor: "Sistema", duracao: "" },
  ],
  c8: [
    { id: "h19", data: "2026-04-15T06:00:00Z", descricao: "Orçamento detalhado enviado por email", atendidoPor: "Lucas Ferreira", duracao: "20 min" },
    { id: "h20", data: "2026-04-12T10:00:00Z", descricao: "Reunião para levantamento de requisitos", atendidoPor: "Lucas Ferreira", duracao: "1h" },
    { id: "h21", data: "2026-04-06T09:00:00Z", descricao: "Lead captado em evento do setor", atendidoPor: "Sistema", duracao: "" },
  ],
};

// ── Contatos: Notas internas ──

export const MOCK_CONTACT_NOTAS: Record<string, NotaInterna[]> = {
  c1: [
    { id: "n1", autor: "Maria Silva", data: "2026-04-14T11:00:00Z", conteudo: "Cliente muito interessado no plano empresarial. Enviar proposta até sexta." },
    { id: "n2", autor: "João Santos", data: "2026-04-12T15:30:00Z", conteudo: "Indicado por parceiro estratégico. Tratar com prioridade." },
  ],
  c2: [
    { id: "n3", autor: "Maria Silva", data: "2026-04-14T11:00:00Z", conteudo: "Cliente muito interessado. Agendar follow-up na próxima semana." },
    { id: "n4", autor: "João Santos", data: "2026-04-12T15:30:00Z", conteudo: "Empresa de médio porte com cerca de 50 funcionários. Budget aprovado." },
  ],
  c3: [
    { id: "n5", autor: "Ana Costa", data: "2026-04-15T07:30:00Z", conteudo: "Demonstração agendada para amanhã às 14h. Preparar ambiente de testes." },
  ],
  c4: [
    { id: "n6", autor: "Pedro Lima", data: "2026-04-10T11:00:00Z", conteudo: "Cliente VIP — conta corporativa com 3 anos de relacionamento." },
    { id: "n7", autor: "Maria Silva", data: "2026-04-05T17:00:00Z", conteudo: "Negociação de renovação em andamento. Desconto de 15% autorizado." },
  ],
  c5: [
    { id: "n8", autor: "Carla Souza", data: "2026-04-15T09:45:00Z", conteudo: "Bug reportado resolvido na versão 2.3.1. Cliente satisfeito." },
  ],
  c6: [],
  c7: [
    { id: "n9", autor: "Beatriz Costa", data: "2026-04-15T09:15:00Z", conteudo: "Interessada em pacote de design + desenvolvimento. Enviar portfólio completo." },
  ],
  c8: [
    { id: "n10", autor: "Lucas Ferreira", data: "2026-04-15T06:30:00Z", conteudo: "Orçamento de R$ 45.000 enviado. Aguardando aprovação da diretoria." },
  ],
};

// ── Contatos: Origens ──

export const MOCK_CONTACT_ORIGENS: Record<string, string> = {
  c1: "Indicação",
  c2: "Formulário do site",
  c3: "Campanha de marketing",
  c4: "Indicação",
  c5: "Orgânico",
  c6: "LinkedIn",
  c7: "Parceiro",
  c8: "Evento",
};

// ── Números WhatsApp ──

export const MOCK_AGENTS = [
  { id: "a1", name: "Mariana S." },
  { id: "a2", name: "João S." },
  { id: "a3", name: "Ana C." },
  { id: "a4", name: "Pedro L." },
  { id: "a5", name: "Carlos S." },
  { id: "a6", name: "Rafael A." },
  { id: "a7", name: "Beatriz M." },
  { id: "a8", name: "Lucas F." },
];

export const MOCK_NUMBERS: NumberCardData[] = [
  {
    instance: {
      id: "i1",
      workspaceId: "w1",
      name: "Vendas SP",
      phone: "+55 34 9 9999-0001",
      evolutionInstanceName: "vendas-sp",
      color: INSTANCE_COLORS[3].value,
      status: "CONNECTED",
      qrCode: null,
      defaultAssignedUserId: "u1",
      createdAt: "2026-01-01T00:00:00Z",
    },
    activeConversations: 142,
    assignedAgents: [MOCK_AGENTS[0], MOCK_AGENTS[1], MOCK_AGENTS[2]],
  },
  {
    instance: {
      id: "i2",
      workspaceId: "w1",
      name: "Suporte RJ",
      phone: "+55 21 9 8888-0002",
      evolutionInstanceName: "suporte-rj",
      color: INSTANCE_COLORS[5].value,
      status: "CONNECTED",
      qrCode: null,
      defaultAssignedUserId: "u2",
      createdAt: "2026-01-05T00:00:00Z",
    },
    activeConversations: 87,
    assignedAgents: [MOCK_AGENTS[3], MOCK_AGENTS[4]],
  },
  {
    instance: {
      id: "i3",
      workspaceId: "w1",
      name: "Atendimento MG",
      phone: "+55 11 9 7777-0003",
      evolutionInstanceName: "atendimento-mg",
      color: INSTANCE_COLORS[4].value,
      status: "DISCONNECTED",
      qrCode: null,
      defaultAssignedUserId: null,
      createdAt: "2026-02-10T00:00:00Z",
    },
    activeConversations: 0,
    assignedAgents: [],
  },
  {
    instance: {
      id: "i4",
      workspaceId: "w1",
      name: "Financeiro SC",
      phone: "+55 47 9 6666-0004",
      evolutionInstanceName: "financeiro-sc",
      color: INSTANCE_COLORS[0].value,
      status: "CONNECTED",
      qrCode: null,
      defaultAssignedUserId: "u3",
      createdAt: "2026-03-01T00:00:00Z",
    },
    activeConversations: 34,
    assignedAgents: [MOCK_AGENTS[5]],
  },
];
